<?php
require './PHPMailer/src/PHPMailer.php';
require './PHPMailer/src/Exception.php';
require './PHPMailer/src/SMTP.php';

//echo (extension_loaded('openssl')?'SSL loaded':'SSL not loaded')."\n";

use PHPMailer\PHPMailer\PHPMailer;

$mail = new PHPMailer;

$mail->setFrom('terenceamungatest@gmail.com');
$mail->addAddress('stondikiyeye@gmail.com');
$mail->Subject = 'Message sent by PHPMailer';
$mail->Body = '<h2>Hello!</h2><p style="color:Blue;">
I am using PHPMailer to send email</p>';

$mail->isHTML(true);
$mail->AltBody = "This message is generated by plain text !";
$mail->IsSMTP();
$mail->SMTPSecure = 'ssl';
$mail->SMTPDebug = 2;
$mail->Host = 'smtp.gmail.com';
$mail->SMTPAuth = true;
$mail->Port = 465;
$mail->Username = 'terenceamungatest@gmail.com';
$mail->Password = 'eighteast';
if(!$mail->send()) {
  echo 'Email is not sent.';
  echo 'Email error: ' . $mail->ErrorInfo;
} else {
  echo 'Email has been sent.';
}
?>